### ISSUE TITLE
Possibly an issue with package.json and latest webpack template

### ISSUE THREAD

**Issue by joemanfoo** [matfish2/vue-stripe#9]
Hi,

Firstly, let me predicate this as a "possible bug" since I am pretty much a blind man feeling his way around the room.  When something sticks me, I scream "bug!".

With the latest, greatest vue-cli and webpack template armed the issue I received is:
`Uncaught SyntaxError: Unexpected token import`
which is coming in on this line in `index.js` located in the `src` folder:
`import StripeCheckout from './StripeCheckout.vue';`

Now editing the line 82 in package.json:
`  "main": "src/index.js",`
to
`  "main": "dist/index.js",`

fixed the issue...

...however I'm not able to get `broadcast` events to fire off in my component but at the moment I'll claim this is my fault and nothing within the code but the jury is still out on that one.  And I tend to agree with other(s) that signal bus isn't the best route to go.

**Comment by matfish2** [comment]
I suggest you stop screaming, and check your babel setup instead. It is clear that your compiler doesn't recognize ES2015, thus the `unexpected token import` error message.
The entry point is correctly set to the `src` folder, and should not be changed.

**Comment by joemanfoo** [comment]
Hi there.

Did get the Bus events trapped, hadn't gotten to the vuejs docs that the bus listener needed to hook in on the `created ()` method.

As for the babel setup I assumed that the `.babelrc` that's part of the webpack template (https://vuejs-templates.github.io/webpack/) covered it.

`{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}`
But I guess that only covers `src/component/*.vue` files and not necessarily the node_modules.

**Comment by pepzwee** [comment]
Babel by default ignores the `node_modules` directory. There's a reason why many projects that are used as dependencies **make sure to compile down before an npm publish**.

**Comment by matfish2** [comment]
@pepzwee, can you give an example to a vue project that pre-compiles?

**Comment by pepzwee** [comment]
This is not about Vue, it's about packages in general

**Comment by matfish2** [comment]
I'm asking for an example, so I can see the structure and implement it.

**Comment by pepzwee** [comment]
@joemanfoo already provided the solution. Also a quote from another issue I found on Github that relates to this issue:

> Modules should be doing their own 6to5 transpiling and providing the compiled "dist" version as the "main" in package.json. 

I see no issue in using `dist` folder as the main instead of `src` since it can make the user's life easier by not having to configure babel to compile inside the `node_modules` folder. Which I even tried doing using webpack with babel, compiling went from a few seconds to half a minute.

**Comment by matfish2** [comment]
I do see an issue. Compiling everything down means that modules might be included more than once. E.g, if I require the `merge` plugin, and the consumer also requires it for his own project, it will end up as a duplicate and bloat the file size. Using the raw version doesn't present this issue, because the compiler will use the cached version.

**Comment by pepzwee** [comment]
Doesn't Node automatically cache all required modules anyway?

**Comment by matfish2** [comment]
I am not sure. I will have to test it to find out
